export const NavLogo = "/assets/Logo.svg";
export const HeroImg = "/assets/HeroImage.jpg";
export const Greeksalad = "/assets/greek_salad.jpg";
export const LemonDessert = "/assets/lemon dessert.jpg";
export const bruchetta = "/assets/bruchetta.jpg";
export const groot = "/assets/groot.jpg";
export const superMan = "/assets/superman.jpg";
export const stefan = "/assets/Stefan_stefancik.jpg";
export const Jake = "/assets/Jake_Nackos.jpg";
export const rest1 = "/assets/restaurant1.jpg";
export const rest2 = "/assets/restaurant2.jpg";
export const footerImg = '/assets/footer_Logo.png'